import { logger } from "@/core/infra/logging/logger";
import {
  analyzePurchaseRequest,
  PR_ANALYSIS_MODEL,
} from "@/modules/purchase-requests/analysis/analyze-purchase-request";
import {
  PR_ANALYSIS_CHECK_NAMES,
  type PrAnalysisResponse,
} from "@/modules/purchase-requests/analysis/analysis-schema";
import {
  PurchaseRequestAnalysisRepository,
  type PurchaseRequestForAnalysis,
} from "@/modules/purchase-requests/analysis/PurchaseRequestAnalysisRepository";
import { sendAnalysisResultToBc } from "@/modules/purchase-requests/callback/send-analysis-to-bc";

const repository = new PurchaseRequestAnalysisRepository();

function buildNoAttachmentsResult(): PrAnalysisResponse {
  return {
    overall_status: "no_document",
    confidence_score: 0,
    document_summary: "No attachments were submitted with this PR; nothing to validate.",
    analyzed_file_name: null,
    field_validations: PR_ANALYSIS_CHECK_NAMES.map(({ checkName, severity }) => ({
      check_name: checkName,
      submitted_value: "N/A",
      extracted_value: "N/A",
      validation_result: "mismatch" as const,
      severity,
      confidence: 0,
    })),
    remarks: "PR was submitted with zero attachments. Document validation could not run.",
  };
}

function buildPrData(pr: PurchaseRequestForAnalysis) {
  return {
    request_date: pr.requestDate,
    vendor_code: pr.vendorCode,
    vendor_name: pr.vendorName,
    vendor_gstin: pr.vendorGstin,
    company_gstin: pr.companyGstin,
    department: pr.department,
    pr_type: pr.prType,
    vendor_invoice_number: pr.vendorInvoiceNumber,
    document_date: pr.documentDate,
    direct_unit_cost: pr.directUnitCost,
    gst_percentage: pr.gstPercentage,
    gst_amount: pr.gstAmount,
    purchase_request_amount: pr.purchaseRequestAmount,
    description: pr.description,
    bank_account_number: pr.bankAccountNumber,
    bank_ifsc: pr.bankIfsc,
    bank_name: pr.bankName,
    service_start_date: pr.serviceStartDate,
    service_end_date: pr.serviceEndDate,
    budget_period: pr.budgetPeriod,
    pos_as_in_vendor_state: pr.posAsInVendorState,
    total_amount_including_gst: pr.totalAmountIncludingGst,
    cgst_percentage: pr.cgstPercentage,
    cgst_amount: pr.cgstAmount,
    sgst_percentage: pr.sgstPercentage,
    sgst_amount: pr.sgstAmount,
    igst_percentage: pr.igstPercentage,
    igst_amount: pr.igstAmount,
    fixed_asset_description: pr.fixedAssetDescription,
    fixed_asset_fa_class_code: pr.fixedAssetFaClassCode,
    fixed_asset_fa_subclass_code: pr.fixedAssetFaSubclassCode,
    depreciation_start_date: pr.depreciationStartDate,
    no_of_depreciation_years: pr.noOfDepreciationYears,
    depreciation_end_date: pr.depreciationEndDate,
    lines: pr.lines.map((line) => ({
      line_no: line.lineNo,
      description: line.description,
      gst_group_code: line.gstGroupCode,
      program_code: line.programCode,
      responsible_dept: line.responsibleDept,
      beneficiary_code: line.beneficiaryCode,
      region_code: line.regionCode,
      subproduct: line.subproduct,
      qty: line.qty,
      direct_unit_cost_excl_vat: line.directUnitCostExclVat,
      line_amount_excluding_vat: line.lineAmountExcludingVat,
    })),
  };
}

/**
 * Runs AI document validation for one PR: fetches the PR + attachments, calls
 * Gemini once (it identifies which attachment is the invoice/quotation to
 * validate among possibly several), stores the result, and flips status to
 * 'analyzed'. Triggered immediately after submission via the route's after().
 *
 * analysisId is generated by the caller (route.ts) at submission time -- not
 * here -- so the same ID returned to BC in the 202 response is the one the
 * completed analysis row ends up with.
 */
export async function runPurchaseRequestAnalysis(
  purchaseRequestId: string,
  analysisId: string,
): Promise<void> {
  const { data: pr, errorMessage: fetchError } =
    await repository.getPurchaseRequestForAnalysis(purchaseRequestId);

  if (fetchError || !pr) {
    logger.error("purchase_request.analysis.fetch_failed", {
      purchaseRequestId,
      errorMessage: fetchError,
    });
    return;
  }

  const { errorMessage: statusError } = await repository.updateStatus(pr.id, "analyzing");
  if (statusError) {
    logger.error("purchase_request.analysis.status_update_failed", {
      purchaseRequestId,
      errorMessage: statusError,
    });
    return;
  }

  try {
    let response: PrAnalysisResponse;

    if (pr.attachments.length === 0) {
      response = buildNoAttachmentsResult();
    } else {
      const downloadedAttachments: { fileName: string; contentType: string; buffer: Buffer }[] = [];
      for (const attachment of pr.attachments) {
        const { data: buffer, errorMessage: downloadError } = await repository.downloadAttachment(
          attachment.storagePath,
        );
        if (downloadError || !buffer) {
          throw new Error(
            `Failed to download attachment ${attachment.fileName}: ${downloadError ?? "unknown error"}`,
          );
        }
        downloadedAttachments.push({
          fileName: attachment.fileName,
          contentType: attachment.contentType,
          buffer,
        });
      }

      const outcome = await analyzePurchaseRequest({
        prId: pr.prId,
        prData: buildPrData(pr),
        attachments: downloadedAttachments,
      });

      if (!outcome.ok) {
        throw new Error(`Gemini analysis failed: ${outcome.reason}`);
      }

      response = outcome.data;
    }

    const analyzedAttachment = response.analyzed_file_name
      ? (pr.attachments.find((attachment) => attachment.fileName === response.analyzed_file_name) ??
        null)
      : null;

    const { errorMessage: insertError } = await repository.insertAnalysis({
      purchaseRequestId: pr.id,
      analyzedAttachmentId: analyzedAttachment?.id ?? null,
      analysisId,
      model: PR_ANALYSIS_MODEL,
      response,
    });

    if (insertError) {
      throw new Error(`Failed to store analysis: ${insertError}`);
    }

    const { errorMessage: finalStatusError } = await repository.updateStatus(pr.id, "analyzed");
    if (finalStatusError) {
      // The analysis row is already stored -- this only failed to flip the PR's own
      // status flag. Log it loudly rather than let the PR sit invisibly stuck on
      // "analyzing" with a completed analysis nobody notices.
      logger.error("purchase_request.analysis.final_status_update_failed", {
        purchaseRequestId: pr.id,
        prId: pr.prId,
        analysisId,
        errorMessage: finalStatusError,
      });
    }

    logger.info("purchase_request.analysis.completed", {
      purchaseRequestId: pr.id,
      prId: pr.prId,
      analysisId,
      overallStatus: response.overall_status,
      confidenceScore: response.confidence_score,
    });

    // Best-effort delivery back to BC -- the analysis itself is already stored and
    // 'analyzed' above, so a callback failure here must never revert that. See
    // sendAnalysisResultToBc's own doc comment for retry/no-op-until-configured behavior.
    try {
      await sendAnalysisResultToBc(analysisId);
    } catch (callbackError) {
      logger.error("purchase_request.bc_callback.unhandled_error", {
        purchaseRequestId: pr.id,
        prId: pr.prId,
        analysisId,
        errorMessage: callbackError instanceof Error ? callbackError.message : "Unknown error.",
      });
    }
  } catch (error) {
    logger.error("purchase_request.analysis.failed", {
      purchaseRequestId,
      errorMessage: error instanceof Error ? error.message : "Unknown analysis failure.",
    });
    // Revert to pending_analysis so a failed run doesn't strand the PR in
    // 'analyzing' forever. There's no auto-retry worker (out of scope for this
    // feature), but this leaves it in a state a manual re-run can pick up.
    await repository.updateStatus(purchaseRequestId, "pending_analysis");
  }
}
