import { logger } from "@/core/infra/logging/logger";
import {
  analyzePurchaseRequest,
  PR_ANALYSIS_MODEL,
} from "@/modules/purchase-requests/analysis/analyze-purchase-request";
import {
  PR_ANALYSIS_CHECK_NAMES,
  type PrAnalysisResponse,
} from "@/modules/purchase-requests/analysis/analysis-schema";
import {
  PurchaseRequestAnalysisRepository,
  type PurchaseRequestForAnalysis,
} from "@/modules/purchase-requests/analysis/PurchaseRequestAnalysisRepository";
import { sendAnalysisResultToBc } from "@/modules/purchase-requests/callback/send-analysis-to-bc";

const repository = new PurchaseRequestAnalysisRepository();

function buildNoAttachmentsResult(): PrAnalysisResponse {
  return {
    overall_status: "no_document",
    confidence_score: 0,
    document_summary: "No attachments were submitted with this PR; nothing to validate.",
    analyzed_file_name: null,
    field_validations: PR_ANALYSIS_CHECK_NAMES.map(({ checkName, severity }) => ({
      check_name: checkName,
      submitted_value: "N/A",
      extracted_value: "N/A",
      validation_result: "mismatch" as const,
      severity,
      confidence: 0,
    })),
    remarks: "PR was submitted with zero attachments. Document validation could not run.",
  };
}

/**
 * direct_unit_cost/gst_percentage/gst_amount/description used to be header
 * columns the 17-check catalog (VC-04/05/06/07/16/17) validates directly. They
 * now live per-line, so these are synthesized: summed cost/GST amounts across
 * lines, the first line's GST % (an approximation -- lines can have differing
 * rates), and all line descriptions joined together.
 */
function buildPrData(pr: PurchaseRequestForAnalysis) {
  const totalDirectUnitCost = pr.lines.reduce(
    (sum, line) => sum + (line.directUnitCostExclVat ?? 0),
    0,
  );
  const totalGstAmount = pr.lines.reduce((sum, line) => sum + line.gstAmount, 0);
  const firstLineGstPercentage = pr.lines[0]?.gstPercentage ?? 0;
  const combinedDescription = pr.lines.map((line) => line.description).join("; ");

  return {
    request_date: pr.requestDate,
    vendor_code: pr.vendorCode,
    vendor_name: pr.vendorName,
    vendor_gstin: pr.vendorGstin,
    company_gstin: pr.companyGstin,
    pr_type: pr.prType,
    vendor_invoice_number: pr.vendorInvoiceNumber,
    document_date: pr.documentDate,
    direct_unit_cost: totalDirectUnitCost,
    gst_percentage: firstLineGstPercentage,
    gst_amount: totalGstAmount,
    purchase_request_amount: pr.purchaseRequestAmount,
    description: combinedDescription,
    bank_account_number: pr.bankAccountNumber,
    bank_ifsc: pr.bankIfsc,
    bank_name: pr.bankName,
    service_start_date: pr.serviceStartDate,
    service_end_date: pr.serviceEndDate,
    budget_period: pr.budgetPeriod,
    pos_as_in_vendor_state: pr.posAsInVendorState,
    total_amount_including_gst: pr.totalAmountIncludingGst,
    lines: pr.lines.map((line) => ({
      line_no: line.lineNo,
      description: line.description,
      department: line.department,
      gst_percentage: line.gstPercentage,
      gst_amount: line.gstAmount,
      gst_group_code: line.gstGroupCode,
      program_code: line.programCode,
      responsible_dept: line.responsibleDept,
      beneficiary_code: line.beneficiaryCode,
      region_code: line.regionCode,
      subproduct: line.subproduct,
      qty: line.qty,
      direct_unit_cost_excl_vat: line.directUnitCostExclVat,
      line_amount_excluding_vat: line.lineAmountExcludingVat,
      cgst_percentage: line.cgstPercentage,
      cgst_amount: line.cgstAmount,
      sgst_percentage: line.sgstPercentage,
      sgst_amount: line.sgstAmount,
      igst_percentage: line.igstPercentage,
      igst_amount: line.igstAmount,
      fixed_asset_description: line.fixedAssetDescription,
      fixed_asset_fa_class_code: line.fixedAssetFaClassCode,
      fixed_asset_fa_subclass_code: line.fixedAssetFaSubclassCode,
      depreciation_start_date: line.depreciationStartDate,
      no_of_depreciation_years: line.noOfDepreciationYears,
      depreciation_end_date: line.depreciationEndDate,
    })),
  };
}

/**
 * Runs AI document validation for one PR: fetches the PR + attachments, calls
 * Gemini once (it identifies which attachment is the invoice/quotation to
 * validate among possibly several), stores the result, and flips status to
 * 'analyzed'. Triggered immediately after submission via the route's after().
 *
 * analysisId is generated by the caller (route.ts) at submission time -- not
 * here -- so the same ID returned to BC in the 202 response is the one the
 * completed analysis row ends up with.
 */
export async function runPurchaseRequestAnalysis(
  purchaseRequestId: string,
  analysisId: string,
): Promise<void> {
  const { data: pr, errorMessage: fetchError } =
    await repository.getPurchaseRequestForAnalysis(purchaseRequestId);

  if (fetchError || !pr) {
    logger.error("purchase_request.analysis.fetch_failed", {
      purchaseRequestId,
      errorMessage: fetchError,
    });
    return;
  }

  const { errorMessage: statusError } = await repository.updateStatus(pr.id, "analyzing");
  if (statusError) {
    logger.error("purchase_request.analysis.status_update_failed", {
      purchaseRequestId,
      errorMessage: statusError,
    });
    return;
  }

  try {
    let response: PrAnalysisResponse;

    if (pr.attachments.length === 0) {
      response = buildNoAttachmentsResult();
    } else {
      const downloadedAttachments: { fileName: string; contentType: string; buffer: Buffer }[] = [];
      for (const attachment of pr.attachments) {
        const { data: buffer, errorMessage: downloadError } = await repository.downloadAttachment(
          attachment.storagePath,
        );
        if (downloadError || !buffer) {
          throw new Error(
            `Failed to download attachment ${attachment.fileName}: ${downloadError ?? "unknown error"}`,
          );
        }
        downloadedAttachments.push({
          fileName: attachment.fileName,
          contentType: attachment.contentType,
          buffer,
        });
      }

      const outcome = await analyzePurchaseRequest({
        prId: pr.prId,
        prData: buildPrData(pr),
        attachments: downloadedAttachments,
      });

      if (!outcome.ok) {
        throw new Error(`Gemini analysis failed: ${outcome.reason}`);
      }

      response = outcome.data;
    }

    const analyzedAttachment = response.analyzed_file_name
      ? (pr.attachments.find((attachment) => attachment.fileName === response.analyzed_file_name) ??
        null)
      : null;

    const { errorMessage: insertError } = await repository.insertAnalysis({
      purchaseRequestId: pr.id,
      analyzedAttachmentId: analyzedAttachment?.id ?? null,
      analysisId,
      model: PR_ANALYSIS_MODEL,
      response,
    });

    if (insertError) {
      throw new Error(`Failed to store analysis: ${insertError}`);
    }

    const { errorMessage: finalStatusError } = await repository.updateStatus(pr.id, "analyzed");
    if (finalStatusError) {
      // The analysis row is already stored -- this only failed to flip the PR's own
      // status flag. Log it loudly rather than let the PR sit invisibly stuck on
      // "analyzing" with a completed analysis nobody notices.
      logger.error("purchase_request.analysis.final_status_update_failed", {
        purchaseRequestId: pr.id,
        prId: pr.prId,
        analysisId,
        errorMessage: finalStatusError,
      });
    }

    logger.info("purchase_request.analysis.completed", {
      purchaseRequestId: pr.id,
      prId: pr.prId,
      analysisId,
      overallStatus: response.overall_status,
      confidenceScore: response.confidence_score,
    });

    // Best-effort delivery back to BC -- the analysis itself is already stored and
    // 'analyzed' above, so a callback failure here must never revert that. See
    // sendAnalysisResultToBc's own doc comment for retry/no-op-until-configured behavior.
    try {
      await sendAnalysisResultToBc(analysisId);
    } catch (callbackError) {
      logger.error("purchase_request.bc_callback.unhandled_error", {
        purchaseRequestId: pr.id,
        prId: pr.prId,
        analysisId,
        errorMessage: callbackError instanceof Error ? callbackError.message : "Unknown error.",
      });
    }
  } catch (error) {
    logger.error("purchase_request.analysis.failed", {
      purchaseRequestId,
      errorMessage: error instanceof Error ? error.message : "Unknown analysis failure.",
    });
    // Revert to pending_analysis so a failed run doesn't strand the PR in
    // 'analyzing' forever. There's no auto-retry worker (out of scope for this
    // feature), but this leaves it in a state a manual re-run can pick up.
    await repository.updateStatus(purchaseRequestId, "pending_analysis");
  }
}
