import {
  BcDocumentType,
  BcEmployeeTransactionType,
  BcGstCredit,
  BcGstSubcategory,
  BcLocationCode,
  BcQuantity,
  BcType,
} from "./types.ts";
import type { BcClaimLineItem, BcClaimPayloadFromDb } from "./types.ts";

/**
 * Inputs to the payload builder.
 *   - db: result of public.get_bc_claim_payload(p_claim_id).
 *   - isVendorPayment: Finance toggle from the modal.
 *   - vendor: present iff isVendorPayment is true. Code/name come from
 *     bc-vendor-search; currencyCode / gstGroupCode / hsnSacCode from
 *     the three bc-reference dropdowns.
 */
export interface BuildInputs {
  db: BcClaimPayloadFromDb;
  isVendorPayment: boolean;
  vendor?: {
    code: string;
    name: string;
    currencyCode: string;
    gstGroupCode: string;
    hsnSacCode: string;
  };
  // Signed URLs generated by index.ts from db.receipt_file_path / bank_statement_file_path.
  // Optional — passed null/undefined when the underlying storage path is null.
  fileUrls?: FileUrls;
}

export interface FileUrls {
  billUrl?: string | null;
  bankStatementUrl?: string | null;
}

export function buildRemarks(db: BcClaimPayloadFromDb, urls: FileUrls): string {
  const head = db.purpose ? `${db.claim_id} - ${db.purpose}` : `${db.claim_id} - `;
  const lines = [head];
  if (urls.billUrl) lines.push(`bill - ${urls.billUrl}`);
  if (urls.bankStatementUrl) lines.push(`bank statement - ${urls.bankStatementUrl}`);
  return lines.join("\n");
}

/**
 * Builds the single flat BcClaimLineItem object posted to BC.
 * Vendor-only fields are spread-omitted (NOT null/empty) when isVendorPayment is false.
 *
 * Amount fields (BC's exact key names — typos and casing match BC's spec):
 *   vendor     → ammountLCY = basic_amount,  Ammount = foreign_basic_amount
 *   non-vendor → ammountLCY = total_amount,  Ammount = foreign_total_amount
 *                (falls back to total_amount when foreign_total_amount is 0,
 *                 since most non-vendor claims have no foreign amount entered)
 *
 * employeeId / employeeName resolution:
 *   - On Behalf → on_behalf_employee_code + on_behalf_of_id's full_name
 *   - Self      → employee_id + submitted_by's full_name
 *   Both resolved server-side by get_bc_claim_payload; we just trust db.
 */
// employeeId and claimNo are sent untruncated. BC enforces its own per-field
// length limits and returns Application_StringExceededLength if exceeded —
// we let that fail loudly so over-long real-data IDs are caught at submission
// time rather than silently mangled.
export function buildBcClaimLineItem(inputs: BuildInputs): BcClaimLineItem {
  const { db, isVendorPayment, vendor, fileUrls = {} } = inputs;

  const employeeId =
    db.submission_type === "On Behalf" && db.on_behalf_employee_code
      ? db.on_behalf_employee_code
      : db.employee_id;

  const ammountLCY = isVendorPayment ? db.basic_amount : db.total_amount;
  const Ammount = isVendorPayment
    ? db.foreign_basic_amount
    : db.foreign_total_amount > 0
      ? db.foreign_total_amount
      : db.total_amount;

  const base: BcClaimLineItem = {
    documentType: BcDocumentType.Invoice,
    locationCode: BcLocationCode,
    type: BcType.GLAccount,
    quantity: BcQuantity,
    gstCredit: BcGstCredit.NonAvailment,
    gstSubcategory: BcGstSubcategory.Ineligible4344,
    employeeTransactionType: BcEmployeeTransactionType.Advance,
    documentDate: db.transaction_date,
    glCode: db.bc_code,
    employeeId,
    employeeName: db.employee_name,
    claimNo: db.claim_id,
    remarks: buildRemarks(db, fileUrls),
    programCode: db.program_code,
    subproductCode: db.sub_product_code,
    responsibleDepartment: db.responsible_department_code,
    beneficiaryDepartment: db.beneficiary_department_code,
    regionCode: db.region_code,
    invoiceRequired: isVendorPayment,
    paymentRequired: db.payment_mode_name === "Reimbursement",
    ammountLCY,
    Ammount,
    // Non-vendor claims are always INR; vendor path overrides via spread below.
    currencyCode: "INR",
  };

  if (!isVendorPayment) {
    return base;
  }

  if (!vendor) {
    throw new Error("vendor inputs required when isVendorPayment is true");
  }

  return {
    ...base,
    currencyCode: vendor.currencyCode,
    vendorInvoiceNo: db.bill_no ?? "",
    vendorCode: vendor.code,
    vendorName: vendor.name,
    gstGroupCode: vendor.gstGroupCode,
    hsnSacCode: vendor.hsnSacCode,
  };
}
